server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: test-service
  mvc:
    #解决knife4j版本兼容问题
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://pve003:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath*:db/*.xml
logging:
  path: ./logs
  level:
    root: info
    '[com.my]': debug


my:
  work:
    config:
      privateKeyPem: |
        -----BEGIN EC PRIVATE KEY-----
        MHQCAQEEIFUmcJTzQ59/1Am2RS1wdYmPvyVTW9vTBIfXkBYRE/VSoAcGBSuBBAAK  
        oUQDQgAEMRSbFUksXVsUefZA8KbUbF8YnaaBFazEKPiJ09yf6cVlnf73YgYlWzV0  
        4RD/KoRUbnqx2S0YFpcKrM+PPMTLwg==
        -----END EC PRIVATE KEY-----
      publicKeyPem: |
        -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEMRSbFUksXVsUefZA8KbUbF8YnaaBFazE  
        KPiJ09yf6cVlnf73YgYlWzV04RD/KoRUbnqx2S0YFpcKrM+PPMTLwg==
        -----END PUBLIC KEY-----